export const completedProjects = [
  {
    city: "Lahore",
    projects: [
      "Wapda House Lahore auditorium",
      "State Bank Building, The Mall",
      "Suparco Building, Ferozepur Road",
      "Underpass on Jail Road, Ferozepur Road and University Campus",
      "Empire Plaza",
      "D-Plaza (parking), Rang Mahal",
      "Ibrahim Trade Centre, Barkat Market",
      "Kamran Baradari Shahdara (Surround by River Ravi",
    ],
  },
  {
    city: "Karachi",
    projects: [
      "National Shipping Corporation Building.",
      "Inter Continental Hotel",
      "Karachi Steam Power Station, West Wharf",
      "Korangi B-power Station.",
      "Sheraton Hotel.",
      "Dawood Centre.",
      "Tibet Commercial Plaza Bundar Road.",
      "Bungalows in Clifton.",
    ],
  },
  {
    city: "Quetta",
    projects: [
      "Governor House",
      "Orchard House",
      "GOC House Head Quarter 33 DIV",
      "GOC House HQ 41 Div",
      "Chaghi House",
      "Commandant House CDSC",
      "Office Head Quarter 12 Corps",
      "Main-Building CDSC",
      "Office H.Q Engineer SC",
      "House commandant Engineer SC",
      "HQ 12 crop Bungalows /JCO/ORS Qtrs",
      "HQ 33 Div Bungalows JCO/ORS Qtrs",
      "HQ 41 Div Bungalows JCO/ORS Qtrs",
      "CDSC Bungalows JCO/ORS Qtrs",
      "49 SDT Officer BKS",
      "Station Supply Depot BKS & JCO's Mess",
      "27 Baloch BKS",
      "PAF Base Samungli BKS & JCO's Mess",
      "State Bank Main Building",
      "Ordnance Depot Main office & Sheds",
      "Garrison Officer Mess",
      "CIV various Plazas /Bungalows and Houses",
      "22 Baloch Mosque",
      "109 Engineer BK",
      "93 EME Bn BKS",
      "CMH Wards",
      "PTV Center",
      "HQ FC office and Bungalows",
      "Khalid Air Base HQ 202 Office",
      "10 Baloch BKS",
      "EME BKS MOQs officer Mess",
      "Officer Mess No 7",
      "10 Avn SQr Khalid Base office",
    ],
  },
  {
    city: "Islamabad",
    projects: [
      "Pakistan Secretarial Buildings.",
      "M.N.A. Hostal",
      "Awan-e-Saddar",
      "Telephone Exchange Building.",
    ],
  },
];
